name: rms-processing
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - fastqc=0.11.9
  - trimmomatic=0.39
  - bowtie2=2.5.0
  - samtools=1.16.1
  - multiqc=1.11
  - bedtools=2.30.0
