get_option <- function(args, opt, dft=NA) {
  ok <- grepl(paste0("^", opt, "="), args)
  if (any(ok)) strsplit(head(args[ok], 1), "=")[[1]][2]
  else dft
}

###### INIT ######

library(ggplot2)
library(dplyr)
library(factoextra)
library(pheatmap)
script_path <- normalizePath(get_option(commandArgs(trailingOnly=F), "--file"))
script_dir  <- dirname(script_path)

args <- commandArgs(trailing = TRUE)
datadir <- as.character(args[1])

# Columns' index in count files
rna_col <- as.numeric(args[2])
position_col <- as.numeric(args[3])
count_col <- as.numeric(args[4])

message(paste("installation directory :", script_dir))
message(paste("data directory :", normalizePath(datadir)))
message(paste("working directory :", getwd()))

source(file.path(script_dir, "merge_counts.R"))
source(file.path(script_dir, "plot_boxplot.R"))
source(file.path(script_dir, "plot_RLE.R"))
source(file.path(script_dir, "plot_heatmap.R"))
source(file.path(script_dir, "plot_COA.R"))
###### LOAD COUNT FILES ######

# fcount_data : list of dataframes
# fcount_names : The list of filenames. Only used to name elements in fcount_data.
# fcount_matrix : a single matrix generated by merging all dataframes from fcount_data
fcount_list <- list.files(datadir,pattern = ".csv",full.names = TRUE)
fcount_names <- basename(fcount_list)
fcount_names <- sub(fcount_names,pattern = "*_5_counts.csv",replacement = "")
fcount_data <- lapply(fcount_list,read.csv,sep = "\t",header = F)
names(fcount_data) <- fcount_names
fcount_matrix <- merge_counts(fcount_data,rna_col,position_col,count_col)

###### CALL TO RMARKDOWN ######

rmarkdown::render(file.path(script_dir, "template.rmd"), output_file = "pipeline_report.html",output_dir = getwd())